config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'route_list/index' # Use this type of route in case there's no model associated with it!

  namespace "user" do
    resources :posts do
      resources :post_images # Nested hierarchy!
    end
  end

  namespace "api" do 
    resources :posts, except: [:new, :edit] do
      resources :post_images, except: [:new, :edit]
    end
  end
  
  #root 'user/posts#index' #Tells rails to route root requests to index action of route_list (routeList) controller
  get '*path', to: "application#fallback_index_html", constraints: ->(request) do
    !request.xhr? && request.format.html?
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_images, dependent: :destroy # Fully defines relationship one to many, each image to one post, and properly deletes it on post delete
  # Plus dependent: symbol lets @post.post_images work grab all those images!

  validates :title, presence: true, length: { minimum: 5} # Built right into Rails Models!

  enum project_type: [ :android, :back_end, :front_end, :gui, :iOS ]
  enum project_size: [ :major_project, :small_project ]

  def self.select_without(*columns)
    select(column_names - columns.map(&:to_s)) # (to_s is shorthand for a to string function passed in to run on all vals in Arr)
  end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post, counter_cache: true
  def self.select_without(*columns)
    select(column_names - columns.map(&:to_s))
  end
end

app/controllers/api/post_images_controller.rb
class Api::PostImagesController < ApiController
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApiController #Using ActionController::API means only render/redirect_to work
  def index
    if params[:project_type] == 'null'
      @posts = Post.find_by github_url: "https://github.com/NLCaceres"
    elsif params[:project_type] != nil
      @posts = Post.where(project_type: params[:project_type])
    else
      @posts = Post.select_without(:created_at, :updated_at).order(:project_size)
    end
    
    render json: @posts.to_json(include: { post_images: { only: [:image_url, :alt_text] } })
  end
  def create
    @post = Post.new(post_params) # New function is built into ruby (basic constructor)
    if @post.save 
      render json: @post.show
    else 
      render 'api/404'
    end
  end
  def show
    begin
      @post = Post.find(params[:id])
      render json: @post.to_json( :only => [:title, :description, :github_url])
    rescue ActiveRecord::RecordNotFound
      render 'api/404'
    end
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      render json: @post.show
    else
      render 'api/404'
    end
  end
  def destroy
    Post.find(params[:id]).destroy
  end

  private
  def post_params
    params.require(:post).permit(:title, :description, :github_url)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def fallback_index_html
    render file: 'public/index.html'
  end
end

app/controllers/user/post_images_controller.rb
class User::PostImagesController < ApplicationController

  http_basic_authenticate_with name: "guest", password: "guest", only: :destroy

  def create
    @post = Post.find(params[:post_id])
    @post_image = @post.post_images.create(image_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id]) #Find a corresponding post
    @post_image = @post.post_images.find(params[:id]) # Find its image within the post images arr
    @post_image.destroy
    redirect_to post_path(@post)
  end

  private
  def image_params
    params.require(:post_image).permit(:image_url, :alt_text)
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController

  http_basic_authenticate_with name: "guest", password: "guest", except: [:index, :show] # Only allow the right users!

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    begin
      @post = Post.find(params[:id]) # Another bonus of using instance vars is that Rails will pass it to the view!
    rescue ActiveRecord::RecordNotFound # If nothing found, then redirect back home!
      redirect_to user_posts_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to [:user, @post.show]
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to user_posts_path
  end

  def create # Render is a method (ruby specifies params like a kotlin infix fun) # It also just shows plaintext at this create path
    # render plain: params[:post].inspect # varName followed by colon is the ruby way of making a key point to a value (in this case a key/symbol/string to a method - params)
    # @post = Post.new(params[:post]) # Variables that start with @ are instance vars accesible to entire class # Ruby classes are ALWAYS capital so Post refers to the class
    # The above doesn't actually work! It would be convenient for rails to easily and quickly assign the params to the model, 
    # but it doesn't and would be a security risk in its present form # Instead we do it manually with the require and permit methods specifying the fields from model
    # @post = Post.new(params.require(:post).permit(:title, :text)) # Proper but not common usage of require/permit
    @post = Post.new(post_params) # Common usage! Pass in a method that returns your params!
    if @post.save # returns true if successful (also does saving while it's at it)
      redirect_to [:user, @post]
    else 
      render 'new'
    end
  end

  private # All methods past this point get marked private!
  def post_params
    params.require(:post).permit(:title, :description, :github_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeReactRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Next lines for hot reloading assets via sprockets (mostly useful for changes in app dir rather than react) (changed due to webpacker in 6.x) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/post_images/_form.html.erb
<%= form_with(model: [:user, @post, @post.post_images.build ], local: true) do |form| %>
  <p>
    <%= form.label :image_url %><br>
    <%= form.text_field :image_url %>
  </p>
  <p>
    <%= form.label :alt_text %><br>
    <%= form.text_area :alt_text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/user/post_images/_post_image.html.erb
<img src="<%= post_image.image_url %>" alt="<%= post_image.alt_text %>" style="height:200px; width=200px;">
<p>
  <strong>Caption: </strong>
  <%= post_image.alt_text %>
</p>
<p>
  <%= link_to 'Destroy Post Images', [:user, post_image.post, post_image], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/user/posts/_form.html.erb
<%= form_with(model: [:user, @post], local: true) do |form| %> 

  <% if @post.errors.any? %> 
    <div id="error-explanation">
      <h2>
        <%=pluralize(@post.errors.count, "error") %>
        prevented this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %> <br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %> <br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :github_url %> <br>
    <%= form.text_field :github_url %>
  </p>
  <p><%= form.submit %></p>
<% end %>

app/views/user/posts/edit.html.erb
<h1>Edit an Old Post!</h1>

<%= render 'form' %>

<% if false %>
<%-#Passing form_with with model makes rails use PATCH (Http method) to update -%>
<%-#Difference is scope: :classModel empties the fields! -%>
<%-#Passing in @post itself will fill in the forms! -%>
<%= form_with(model: @post, local: true) do |form| %> 

  <% if @post.errors.any? %> 
    <div id="error-explanation">
      <h2>
        <%=pluralize(@post.errors.count, "error") %>
        prevented this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %> <br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %> <br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :image_url %> <br>
    <%= form.text_field :image_url %>
  </p>
  <p>
    <%= form.label :github_url %> <br>
    <%= form.text_field :github_url %>
  </p>
  <p><%= form.submit %></p>
<% end %>
<% end %>

<%= link_to 'Back', user_posts_path %>

app/views/user/posts/index.html.erb
<h1>All Posts</h1>

<%= link_to 'Create a New Post', new_user_post_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image URL</th>
    <th>Github URL</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.description %></td>
      <% post.post_images.each do |post_image| %>
        <td><img src="<%= post_image.image_url %>" alt="<%= post_image.alt_text %>" style="height:200px; width=200px;"></td>
      <% end %>
      <td><%= post.github_url %></td>
      <td><%= link_to 'Show', user_post_path(post) %></td>
      <td><%= link_to 'Edit', edit_user_post_path(post) %></td>
      <td><%= link_to 'Destroy', user_post_path(post), method: :delete, data: { confirm: 'Are you sure' } %></td>
      <%-# Big diff here is options at the end, http DELETE and a confirmation dialog brought to you by rails-ujs in application.html.erb -%>
    </tr>
  <% end %>
</table>

app/views/user/posts/new.html.erb
<h1>Write a New Post!</h1>

<%= render 'form' %>

<% if false %> 
This if false block actually works as a block comment! 
<%-# Form builder object, specifying it's for post and the path-%>
<%= form_with scope: :post, url: posts_path, local: true do |form| %> 

<%- #The question mark indicates a method returns a bool -%>
  <% if @post.errors.any? %> 
    <div id="error-explanation">
      <h2>
        <%- # Simple helper func to pluralize the string if count > 1 -%>
        <%=pluralize(@post.errors.count, "error") %>
        prevented this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%- #In the event that there are errors, rails actual wraps the following fields with a div of class field_with_errors that you can style with CSS -%>

  <p>
    <%= form.label :title %> <br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %> <br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :image_url %> <br>
    <%= form.text_field :image_url %>
  </p>
  <p>
    <%= form.label :github_url %> <br>
    <%= form.text_field :github_url %>
  </p>
  <p><%= form.submit %></p>
<% end %>
<% end %>

<%= link_to 'Back', user_posts_path %>

app/views/user/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<% if false %>
<p>
  <strong>Image URL:</strong>
  <img src="<%= @post.image_url %>" alt="Words" style="height: 300px; width=300px;">
  <%= @post.image_url %>
</p>
<% end %>

<h2>Post Images</h2>
<%-#In place of array.each func render on them! Simple as that with Rails-%>
<%= render @post.post_images %>

<h2>Add image links!</h2>
<%= render 'user/post_images/form' %>

<p>
  <strong>Github URL:</strong>
  <%= @post.github_url %>
</p>

<%= link_to 'Back', user_posts_path %>
<%= link_to "Edit", edit_user_post_path(@post) %>